FROM ghcr.io/actions/actions-runner:2.326.0
# for latest release, see https://github.com/actions/runner/releases

USER root

# install curl and jq
RUN apt-get update && apt-get install -y curl jq apt-utils ca-certificates wget \
    dnsutils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


    #sudo apt-get install -y wget apt-transport-https software-properties-common

    # Get the version of Ubuntu
#RUN source /etc/os-release
    
    # Download the Microsoft repository keys
RUN wget -q https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb
    
    # Register the Microsoft repository keys
RUN dpkg -i packages-microsoft-prod.deb
    
    # Delete the Microsoft repository keys file
RUN rm packages-microsoft-prod.deb
    
    # Update the list of packages after we added packages.microsoft.com
RUN apt-get update

    
    ###################################
    # Install PowerShell
RUN apt-get install -y powershell
    
    # Start PowerShell
    #pwsh

# Install Az PowerShell module
RUN pwsh -Command "Install-Module -Name Az -Scope AllUsers -Force -AllowClobber"

# Install Azure CLI v2.72.0 manually
RUN curl -sL -o azure-cli_2.72.0-1_all.deb https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.72.0-1_all.deb && \
    apt-get install -y ./azure-cli_2.72.0-1_all.deb && \
    rm azure-cli_2.72.0-1_all.deb

COPY github-actions-runner/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

USER runner

ENTRYPOINT ["./entrypoint.sh"]
