FROM ghcr.io/actions/actions-runner:2.304.0
# for latest release, see https://github.com/actions/runner/releases

USER root

# install curl and jq
RUN apt-get update && apt-get install -y curl jq apt-utils ca-certificates wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


    #sudo apt-get install -y wget apt-transport-https software-properties-common

    # Get the version of Ubuntu
#RUN source /etc/os-release
    
    # Download the Microsoft repository keys
RUN wget -q https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb
    
    # Register the Microsoft repository keys
RUN dpkg -i packages-microsoft-prod.deb
    
    # Delete the Microsoft repository keys file
RUN rm packages-microsoft-prod.deb
    
    # Update the list of packages after we added packages.microsoft.com
RUN apt-get update
    
    ###################################
    # Install PowerShell
RUN apt-get install -y powershell
    
    # Start PowerShell
    #pwsh

# Install Az PowerShell module
RUN pwsh -Command "Install-Module -Name Az -Scope AllUsers -Force -AllowClobber"

RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

COPY github-actions-runner/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

USER runner

ENTRYPOINT ["./entrypoint.sh"]
