FROM ghcr.io/actions/actions-runner:2.304.0
# For latest release: https://github.com/actions/runner/releases

USER root

# Install core tools, PowerShell, and setup Microsoft repo
RUN apt-get update && apt-get install -y \
    curl \
    jq \
    apt-utils \
    ca-certificates \
    wget \
    gnupg \
    software-properties-common \
    powershell && \
    wget -q https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    rm packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install -y azure-cli && \
    az bicep install && \
    az bicep upgrade && \
    pwsh -Command "Install-Module -Name Az -Scope AllUsers -Force -AllowClobber" && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy and configure runner entrypoint script
COPY github-actions-runner/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

USER runner

ENTRYPOINT ["./entrypoint.sh"]
